### ISSUE TITLE
Add support for vma (vk-mem-rs)

### ISSUE THREAD

**Issue by filnet** [adrien-ben/imgui-rs-vulkan-renderer#11]
I'd like to add support for vma (vk-mem-rs) as a feature.

Note that it will not provide support for  custom allocators.

**Comment by filnet** [comment]
I had a quick look and it seems a bit complicated to add support for vk-mem-rs as a feature.

The main reason is that vk_mem takes over buffer & memory allocation : you have to use a `vk_mem::Allocator` which will return a buffer and a `vk_mem::Allocation` (not a `ash::vk::DeviceMemory`).
See https://github.com/gwihlidal/vk-mem-rs#example.

So optionally supporting vk-mem-rs looks a bit cumbersome at this stage:
* it would require to introduce an abstraction on top of `ash::vk::DeviceMemory` and `vk_mem::Allocation`
* and/or have a lot #[cfg(feature = "???")] all over the place

Another approach would be to use vm-mem-rs internally and make it possible for a user to optionally provide it's own `vk_mem::Allocator` if needed.
But that approach would exclude adding support for vulkan allocators.

@adrien-ben, please provide feedvack.

**Comment by adrien-ben** [comment]
Hi, 

I am not too familiar with vma, so I had to read through the docs. 

I would like it to be optional. Honestly, I prefer the idea of having it as a feature. I did not have the time to dig into the code to see how hard it would be to integrate.

If making it a feature is too complicated, I'm ok with the last option. We would just have to extend the `RendererVkContext` to add something like:

```rust
fn allocator(&self) -> Option<vk_mem::Allocator> {
    None
}
```

**Comment by filnet** [comment]
Thanks for the feedback.

I also would like to make it optional. Feels better and does not close the door to later adding support for regular vk allocators.

For now, I'll do a native integration of vma (not as a feature) to see what the required changes look like.
Then we can decide together where to go from there.

**Comment by adrien-ben** [comment]
Sounds good to me. Feel free to open a draft PR.

**Comment by matthewjberger** [comment]
If it helps, I have some rust/vulkan code using the vk-mem-rs crate here:

https://github.com/matthewjberger/dragonglass/blob/develop/crates/dragonglass_vulkan/src/core/resources/buffer.rs

and I initialize the allocator here:

https://github.com/matthewjberger/dragonglass/blob/develop/crates/dragonglass_vulkan/src/core/context.rs
