### ISSUE TITLE
Renderer appears to not work on HiDpi displays

### ISSUE THREAD

**Issue by photex** [adrien-ben/imgui-rs-vulkan-renderer#13]
I'm trying to figure out whats missing exactly. If you have any ideas I'm happy to hear them and send a PR with anything that ends up working. :+1:

**Comment by adrien-ben** [comment]
Hi,

Can you provide more details about what is not working ? Is it not rendering at all or not at the proper scale ? Have you tried running the exemples with validation layers enabled ?

**Comment by photex** [comment]
The issue seems to be that imgui quads are all projected at the physical resolution instead of the logical (aka not at the proper scale as you've said). Events and scissor regions all appear to be correct otherwise.
I'm on the road until this evening. I'll make a screen cap of the issue asap. 
This issue occurs with any of the example in this repo.

**Comment by adrien-ben** [comment]
Thanks for the details. When you have time could you try this branch https://github.com/adrien-ben/imgui-rs-vulkan-renderer/tree/fix_hidpi_scale and tell me if the result are better ? 

I was able to reproduce the issue by changing the rendering scale of Windows and the change fixed it for me.

**Comment by photex** [comment]
Confirmed that this fixes the issue for me. :D Thanks for laying it out like that.

I stepped through everything with the debugger and came to the conclusion that the ortho projection was the problem, but I was convinced that the source of the problem lay elsewhere and that I must be using something wrong upstream. :D

**Comment by adrien-ben** [comment]
Nice :), for some reason I applied the window's scale to the projection.

Thanks for raising the issue now I know I can change Windows UI scale to test that kind of stuff ! :)

**Comment by adrien-ben** [comment]
Version 0.6.1 is now available :) Have a nice day !

**Comment by photex** [comment]
Awesome! Thanks for wrapping that up so quickly.
