### ISSUE TITLE
Broken as vk-mem fails to build with ash version >= 0.33

### ISSUE THREAD

**Issue by bennywwg** [adrien-ben/imgui-rs-vulkan-renderer#16]
The issue mentioned [here ](https://github.com/gwihlidal/vk-mem-rs/issues/54) has broken this repo.

It can temporarily be resolved replacing line 24 of Cargo.toml with
`
vk-mem = { git = "https://github.com/Chris--B/vk-mem-rs", optional = true }
`

However this restricts the ash version to <0.33, and depends on some random repo. I don't know enough about cargo to propose a better solution.

**Comment by thargy** [comment]
See [this issue](https://github.com/gwihlidal/vk-mem-rs/issues/54) which explains the problem of the breaking change in `ash` and recommends changing to [`gpu-allocator`](https://crates.io/crates/gpu-allocator).

I started looking at doing this work, but it's non-trivial and would prefer to know if dropping `vk-mem` for `gpu-allocator` would be accepted, or whether you'd prefer a different approach (which I'd recommend), i.e. supporting unknown custom allocators in the library, e.g. through the `AllocatorTrait`.  At which point a separate crate could be made to support `gpu-allocator` integration?

**Comment by adrien-ben** [comment]
Hi,

I will probably start by releasing a fix version setting an upper bound to the ash version that can be used.

I don't think it makes too much sense for now to make the library super generic and allow for custom allocators to be added via other crates. I think moving to gpu-allocator is probably the option i would prefer for now. 

What do you think ?

**Comment by thargy** [comment]
> What do you think ?

Having spent the entire day trying to find a GUI framework over `ash` (which I need as I'm trying to do RayTracing and `ash` seems to be the only one supporting the extensions so far), the `vk-mem` issue (as you say it's the on with an unconstrained import) is killing pretty much every crate out there, and causing an exodus to `gpu-allocator`.  However, no one seems to have done the work yet [see this for example](https://github.com/MatchaChoco010/egui_winit_ash_vk_mem/issues/3) which is extra-painful for people getting started.

I think the framework that updates most reliably and quickly will gain some support.

**Comment by adrien-ben** [comment]
I think I could start working on it later this week. In the meantime couldn't you use this library without the `vkmem` feature ?

**Comment by thargy** [comment]
> I think I could start working on it later this week. 

That would be great!  I didn't want to imply that you had to update to win my 'amazing patronage' :grin:, it was more a comment on the general instability of Rust game development at the moment, and the impact a single popular crate going quiet can have.

>In the meantime couldn't you use this library without the `vkmem` feature?

Yes, that's how I'm starting, and I got your examples to run fine using:
```
vk-mem = { git = "https://github.com/Chris--B/vk-mem-rs", optional = true }
```

So unlike some of the other frameworks like @cheako's [ash-tray-rs](ash-tray-rs) (which he mentions in #17 and I spent an afternoon trying to get to work with zero-documentation! Though, tbf it looks promising otherwise) I can at least start making _some_ progress!

**Comment by adrien-ben** [comment]
> That would be great! I didn't want to imply that you had to update to win my 'amazing patronage' 😁, it was more a comment on the general instability of Rust game development at the moment, and the impact a single popular crate going quiet can have.

Haha, no don't worry, that's not how I understood it :) 

> Yes, that's how I'm starting, and I got your examples to run fine using: ...

Ok nice, I'll get back to you when I make some progress.

**Comment by adrien-ben** [comment]
Hi, I know it's been a while but I finally found some time to look at this and if you're still interested in it #21 is now almost done.

It reworks the api to get rid of the `RendererVkContext` and adds support for gpu-allocator. I'm still not sure about the api (especially the gpu-allocator integration) so I'll will wait a few days before merging it. Maybe something will click in my head or someone will suggests improvements.

**Comment by thargy** [comment]
I moved to C++ for a few months, and then back to C#, where I'm currently writing a Vulkan library for easy bootstrapping 🤣 I am too easily distracted!  I enjoyed Rust a great deal, but it had some scenarios where you could too easily fall into the pit of despair of thinking you had a nice design, only to come up against a hard roadblock after a lot of work.  I'm optimistic about its future, but I'm not sure it's quite there for me yet.

**Comment by adrien-ben** [comment]
hey @thargy.
Yeah I definitely understand where you are coming from. Rust is pretty hard some times. I am also struggling  especially when I try to design public apis ^^. 

Thanks for replying anyways ! Is your library public yet or do you plan to make it at some point ?

**Comment by thargy** [comment]
> Thanks for replying anyways ! Is your library public yet or do you plan to make it at some point ?

It's getting close and will be at [DevDecoder.Vulkan](https://github.com/DevDecoder/DevDecoder.Vulkan) when a little bit more usable.  Currently, I am polishing the broad design strokes and making sure it's broadly future proof before I make it public.  I retired last year, so I only do FOSS stuff now.
