### ISSUE TITLE
Use with existed renderpass show rasterizationSamples does not match the number of samples of the RenderPass color and/or depth attachment. 

### ISSUE THREAD

**Issue by Latias94** [adrien-ben/imgui-rs-vulkan-renderer#33]
My application's [renderpass](https://github.com/Latias94/eureka/blob/main/crates/illuminate/src/vulkan/render_pass.rs) has three attachment: [color, depth, color_resolve], then create imgui renderer by [`Renderer::with_gpu_allocator` ](https://github.com/Latias94/eureka/blob/main/crates/illuminate/src/vulkan/imgui.rs#L65) with my existed renderpass. then show error as follow.

related codes: 
* new [renderer.rs#L188](https://github.com/Latias94/eureka/blob/main/crates/illuminate/src/vulkan/renderer.rs#L188)
* cmd_draw [swapchain.rs#L464](https://github.com/Latias94/eureka/blob/main/crates/illuminate/src/vulkan/swapchain.rs#L464)

I try to find the usage example from your repo: [gltf-viewer-rs](https://github.com/adrien-ben/gltf-viewer-rs) and [vulkan-examples-rs](https://github.com/adrien-ben/vulkan-examples-rs), but it seems both of them are using Dynamic Rendering feature.

Should I create another renderpass, framebuffer, image and image_view? I want to create a game engine editor like [adriengivry/Overload](https://github.com/adriengivry/Overload), should I create another Vulkan renderer for imgui?

My project code: [Latias94/eureka](https://github.com/Latias94/eureka)
Just go with `cargo r`

```
[Validation] [VUID-VkGraphicsPipelineCreateInfo-multisampledRenderToSingleSampled-06853 (822655899)] : 
Validation Error: [ VUID-VkGraphicsPipelineCreateInfo-multisampledRenderToSingleSampled-06853 ] Object 0: handle = 0x14c137eaad0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x3108bb9b | 
vkCreateGraphicsPipelines: pCreateInfo[0].pMultisampleState->rasterizationSamples (1) does not match the number of samples of the RenderPass color and/or depth attachment. 
The Vulkan spec states: If the pipeline is being created with fragment output interface state, and none of the VK_AMD_mixed_attachment_samples extension, the VK_NV_framebuffer_mixed_samples extension, 
or the multisampledRenderToSingleSampled feature are enabled, and if subpass uses color and/or depth/stencil attachments, 
then the rasterizationSamples member of pMultisampleState must be the same as the sample count for those subpass attachments 
(https://vulkan.lunarg.com/doc/view/1.3.236.0/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-multisampledRenderToSingleSampled-06853)
```

```
[Validation] [VUID-vkCmdDrawIndexed-rasterizationSamples-04740 (-329854293)] : Validation Error: [ VUID-vkCmdDrawIndexed-rasterizationSamples-04740 ] Object 0: handle = 0x2b424a0000000034, type = VK_OBJECT_TYPE_PIPELINE; Object 1: handle = 0xdd3a8a0000000015, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xec56d2ab | 
vkCmdDrawIndexed: In VkPipeline 0x2b424a0000000034[] the sample count is VK_SAMPLE_COUNT_1_BIT while the current VkRenderPass 0xdd3a8a0000000015[] has VK_SAMPLE_COUNT_8_BIT and they need to be the same. 
The Vulkan spec states: If rasterization is not disabled in the bound graphics pipeline, and neither the VK_AMD_mixed_attachment_samples nor the VK_NV_framebuffer_mixed_samples extensions are enabled, 
then VkPipelineMultisampleStateCreateInfo::rasterizationSamples must be the same as the current subpass color and/or depth/stencil attachments 
(https://vulkan.lunarg.com/doc/view/1.3.236.0/windows/1.3-extensions/vkspec.html#VUID-vkCmdDrawIndexed-rasterizationSamples-04740)
```

**Comment by adrien-ben** [comment]
Hi ! 
I think it would make sense to render the ui in a separate render pass.
Also I am not sure it makes a tone of sense to use MSAA for UI.
 
Having a separate render pass for UI is interesting  because you could for example render your scene at a lower resolution but still render UI at native. Also if you want to implement some post processing at some point it make sense to render the UI at the very end of your frame.

**Comment by Latias94** [comment]
Thanks for your quick reply!
Another Vulkan newbie question like https://github.com/ocornut/imgui/issues/5110#issue-1167942766

1. 
![image](https://user-images.githubusercontent.com/13315417/215239603-359d2a3a-836f-4eb8-9a27-f416617dbc88.png)
If I want to integrate imgui as a setting panel(like your gltf-viewer), does it mean I need to render imgui to my existed renderpass and framebuffer? and I need to modify my existed renderpass so as to adapt to imgui, for example no more msaa?

2. 
![image](https://user-images.githubusercontent.com/13315417/215239730-32a2dd5e-d935-460d-bd52-a19e579f0a5b.png)
For this one, I think this is which you recommand, is to render ui in separate renderpass, and render the sceen as a texture then show in imgui window.

Correct me if you have spare time, thank you.

**Comment by adrien-ben** [comment]
1. 
Yes you would need a new renderpass and framebuffer. Something like:
- Render your scene with msaa in framebuffer 1 (with swapchain image as resolve attachment)
- Render UI without msaa in framebuffer 2 (with swapchain image as color attachment)
It's been a while since I used render passes and framebuffers so I am not 100% positive this works as is but it should be close.

2.
If by this one you means integrate your final image in an editor like UI. I would render the scene in an image which is not part of the swapchain. Then render the UI and use the image containing the scene as a texture in the UI. Hope it makes sense ;)
I haven't done it myself.

**Comment by Latias94** [comment]
![image](https://user-images.githubusercontent.com/13315417/215276712-9455eae4-6f0d-4e56-bb79-c73e693faa43.png)

it work finally
