### ISSUE TITLE
[Question] How to set background image?

### ISSUE THREAD

**Issue by ngortheone** [adrien-ben/imgui-rs-vulkan-renderer#35]
Sorry for noob question, don't understand much about vulkan (yet)

https://github.com/adrien-ben/imgui-rs-vulkan-renderer/blob/master/examples/common/mod.rs#L1048
Here you set background color to white.

How do I set a background image?
Please feel free to point me at some reading if my answer is too noobish :D 

Thanks

**Comment by filnet** [comment]
It is not as simple as setting the background color.

You can take a look at this example: https://github.com/adrien-ben/imgui-rs-vulkan-renderer/blob/master/examples/custom_textures.rs.

**Comment by filnet** [comment]
And https://docs.rs/imgui-rs-vulkan-renderer/latest/imgui_rs_vulkan_renderer/struct.Renderer.html#method.textures
