### ISSUE TITLE
How to make a triangle example?

### ISSUE THREAD

**Issue by mackst** [adrien-ben/imgui-rs-vulkan-renderer#36]
Hi,

How to make example like this
https://github.com/imgui-rs/imgui-rs/blob/main/imgui-glow-renderer/examples/glow_02_triangle.rs
with ash and this render backend?

**Comment by adrien-ben** [comment]
Hi,

You might want to take a look at https://github.com/adrien-ben/vulkan-triangle-rs/blob/master/src/main.rs.
This is a simple triangle example. 

Then you can look at the code in `/examples/common` to see how to integrate this library in an app using ash.
